# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

pool:
  vmImage: ubuntu-latest

steps:
- script: echo Hello, world!
  displayName: 'Run a one-line script'

- script: |
    echo Add other tasks to build, test, and deploy your project.
    echo See https://aka.ms/yaml
  displayName: 'Run a multi-line script'
- task: InstallSSHKey@0
  inputs:
    knownHostsEntry: |
      ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIN6CYxqbIv+PWd4tWwxKZyMmUmjmRzyU7Iyq1rQ3G01x
      52.191.131.160 ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQDHZE8uSHYYJOBww4eQxgfMl89kuqc+SuzrdAEx176Kgc0yMF6yXXXUSio+MJiZNg0wh9io0eqywUUf+5FM9/Y9gx4I/MImg8hs99lRxT/c5z5epPO9RAhJRVorqN0JgjUXZP8kQa7+YSu2ESXfqJz5LAOEF8bPBGfz1froaXxhYdD8qrZ4aetVcaUZq6Z/t3Ezugzg3i3DQ9EpzXA9DtO0j13qSfWfiQNFbD9nVLIkMyO7iNgHAYqi91bvZhSNBUxqECtyiczT/iqi+5oM50n2/P96aBuCKACZmDLW03ONK3J2szIzate1KeGQCD28KzArB1YqtY9lyOC3Me32lDAR
      52.191.131.160 ecdsa-sha2-nistp256 AAAAE2VjZHNhLXNoYTItbmlzdHAyNTYAAAAIbmlzdHAyNTYAAABBBGlYO103SfmfPCgKf1VHEzMvo/bg6YPy4qRqk+fWl9IQcovdpkN6FVkAIQ/UlEyUgB3C74TLcurmJbE8gtkSxkg=
    sshKeySecureFile: 'Flock-of-Hawks-VM_key.pem'
- task: SSH@0
  inputs:
    sshEndpoint: 'Flock-of-Hawks-VM'
    runOptions: 'commands'
    commands: 'sudo apt-get install maven -y'
    readyTimeout: '20000'
- task: SSH@0
  inputs:
    sshEndpoint: 'Flock-of-Hawks-VM'
    runOptions: 'inline'
    inline: |
      sudo apt-get install tomcat8
      sudo git clone https://github.com/davidpearl20/team_e_p1_orm.git
      sudo git clone https://github.com/davidpearl20/team_e_p1_webapp.git
      cd /home/dajpearl/team_e_p1_orm
      sudo mvn compile
      sudo mvn install
      sudo mvn package
      cd /home/dajpearl/team_e_p1_webapp
      sudo mvn compile
      sudo mvn install
      sudo mvn package
    failOnStdErr: false
    readyTimeout: '20000'
- task: SSH@0
  inputs:
    sshEndpoint: 'Flock-of-Hawks-VM'
    runOptions: 'inline'
    inline: |
      sudo cp /home/dajpearl/team_e_p1_webapp/target/p1-webapp-0.9.war  /var/lib/tomcat8/webapps
            cd /usr/share/tomcat8/bin
            sudo mkdir /usr/share/tomcat8/logs
            sudo ./catalina.sh start
            cd /home/dajpearl/team_e_p1_webapp
            sudo mvn install tomcat7:deploy
    failOnStdErr: false
    readyTimeout: '20000'

- task: SSH@0
  inputs:
    sshEndpoint: 'Flock-of-Hawks-VM'
    runOptions: 'commands'
    commands: 'sudo apt-get install python-psycopg2 -y'
    failOnStdErr: false
    readyTimeout: '20000'
- task: Ansible@0
  inputs:
    ansibleInterface: 'agentMachine'
    playbookPathOnAgentMachine: './new_db_setup.yml'
    inventoriesAgentMachine: 'file'
    inventoryFileOnAgentMachine: './inventory'
    sudoEnabled: true