variables:
- name: BuildParameters.mavenPOMFile
  value: pom.xml
name: $(date:yyyyMMdd)$(rev:.r)
resources:
  repositories:
  - repository: self
    type: git
    ref: main
jobs:
- job: Job_1
  displayName: Agent job 1
  pool:
    vmImage: ubuntu-16.04
  steps:
  - checkout: self
  - task: MavenAuthenticate@0
    inputs:
      artifactsFeeds: 'webapp'
  - task: Maven@3
    displayName: Maven pom.xml
    inputs:
      mavenPOMFile: $(BuildParameters.mavenPOMFile)
  - task: CopyFiles@2
    displayName: 'Copy Files to: $(build.artifactstagingdirectory)'
    condition: succeededOrFailed()
    inputs:
      SourceFolder: $(system.defaultworkingdirectory)
      Contents: '**/*.jar'
      TargetFolder: $(build.artifactstagingdirectory)
  - task: DownloadPipelineArtifact@2
    displayName: Download Pipeline Artifact
    inputs:
      path: pkgs.dev.azure.com/revature-training-uta/24909f86-8d03-4826-8947-55d471b47b72/_packaging/webapp/maven/v1/
  - task: CopyFiles@2
    displayName: 'Copy Files to: pkgs.dev.azure.com/revature-training-uta/24909f86-8d03-4826-8947-55d471b47b72/_packaging/webapp/maven/v1'
    inputs:
      TargetFolder: pkgs.dev.azure.com/revature-training-uta/24909f86-8d03-4826-8947-55d471b47b72/_packaging/webapp/maven/v1
  - task: CopyFiles@2
    displayName: 'Copy Files to: pkgs.dev.azure.com/revature-training-uta/24909f86-8d03-4826-8947-55d471b47b72/_packaging/webapp/maven/v1/eorm-1.0.jar'
    inputs:
      TargetFolder: pkgs.dev.azure.com/revature-training-uta/24909f86-8d03-4826-8947-55d471b47b72/_packaging/webapp/maven/v1/eorm-1.0.jar
  - task: CopyFiles@2
    inputs:
      Contents: '**/*.jar'
      TargetFolder: '/home/vsts/work/1/s/'
  - task: PublishPipelineArtifact@1
    inputs:
     targetPath: '$(Pipeline.Workspace)'
     artifact: 'eteam:eorm:jar:1.0'
     publishLocation: 'pipeline'
  