---
- hosts: all
  become: yes

  tasks:
    - name: install pip3
      package:
        name: python3-pip
        state: latest
    - name: python2
      package:
        name: python2
        state: latest
    - name: install setuptools
      pip:
        cmd: 'pip install setuptools'
    - name: import psycopg2-binary
      pip: 
        cmd: 'pip install psycopg2'
    - name: Create a new database
      community.postgresql.postgresql_db:
        name: airline_db
        