---
- hosts: all
  become: yes

  tasks:
    - name: install pip
      package:
        name: python3-pip
        state: latest
    - name: install setuptools
      pip:
        name: python2-setuptools
        state: latest
    - name: import psycopg2-binary
      pip: 
        name: psycopg2-binary
        state: present
    - name: Create a new database
      community.postgresql.postgresql_db:
        name: airline_db
        