---
- hosts: all
  become: yes

  tasks:
    - name: install pip3
      package:
        name: python3-pip
        state: latest
    - name: install setuptools
      ansible.builtin.command:
        cmd: 'pip3 install --upgrade pip setuptools'
    - name: install psycopg2
      ansible.builtin.command:
        cmd: 'pip install psycopg2-binary'
    - name: Create a new database
      community.postgresql.postgresql_db:
        name: airline_db
        