---
- hosts: all
  tasks:
    - name: install packages
      ansible.builtin.package:
        name: 
          - maven
          - postgresql-12
          - postgresql-contrib-9.x
          - libpq-dev	
          - postgresql-server-dev-12	
          - pgadmin4